[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
dependencies = ["run"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--workspace"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run]
command = "cargo"
args = ["run", "--package=atlantsh", "--bin=atlsh"]
dependencies = ["build"]
